player-ui/tools

.circleci/config.yml, .github/workflows/canary.yml
=> Canary support

.circleci/config.yml
Add Circle workflow for building PRs from forked branches.
=> add forked pr workflow

xlr/converters/src/__tests__/__snapshots__/player.test.ts.snap, xlr/converters/src/__tests__/player.test.ts, xlr/types/src/core.ts, xlr/utils/BUILD, xlr/utils/src/__tests__/__snapshots__/annotations.test.ts.snap, xlr/utils/src/__tests__/annotations.test.ts, xlr/utils/src/__tests__/helpers/test-helpers.ts, xlr/utils/src/annotations.ts
- Updating feature/drag-and-drop branch with the latest from main
- added test-helper for xlr / utils.
- all tests still run green.
- verified drag and drop app still functions as expected.
=> Updating Feature/drag and drop branch with latest.

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, README.md
- Copy PR template from [player](https://github.com/player-ui/player)
- Add `CONTRIBUTING.md`
- Update README with link to CONTRIBUTING and add some content from [player](https://github.com/player-ui/player) README
=> Add CONTRIBUTING.md

language/json-language-service/BUILD, language/json-language-service/package.json, language/typescript-expression-plugin/BUILD, language/typescript-expression-plugin/package.json, xlr/sdk/BUILD, xlr/sdk/package.json
=> Make test dependencies devDependencies

cli/BUILD
Fix CLI build pulling in non-runtime dependencies
=> Break out dev/hard cli deps

.intuitgithookrc, vitest.config.ts, xlr/utils/src/__tests__/ts-helpers.test.ts, xlr/utils/src/__tests__/type-check.test.ts, xlr/utils/src/ts-helpers.ts
Adding more tests to XLR helper functions and cleaning up some of their implementations where appropriate. 
Add more test coverage for XLR helper functions
=> XLR Helper Functions Tests

cli/README.md, language/dsl/README.md
- Corrected package name on main DSL README file.
- Added `validate` command plus options for CLI README file.
=> [Docs] DSL pckg name and CLI validate command docs update

devtools/plugins/desktop/basic/src/WrapperComponent.tsx, devtools/plugins/desktop/basic/src/constants/index.ts, devtools/plugins/desktop/basic/src/content/schema/index.ts, devtools/plugins/desktop/basic/src/content/views/EditorView.tsx, devtools/plugins/desktop/basic/src/content/views/index.ts, devtools/plugins/desktop/basic/src/index.tsx, devtools/plugins/desktop/basic/src/types.ts, package.json, pnpm-lock.yaml
Adds an Editor view to the dev tools basic plugin that allows overriding the inspected Player's flow.
https://github.com/player-ui/tools/assets/26394217/1376b656-c745-4b97-ae4a-7f271661287d
=> feat: adds editor view to basic devtools plugin

language/dsl/src/__tests__/asset-api.test.tsx, language/dsl/src/__tests__/helpers/asset-library.tsx, language/dsl/src/auto-id.tsx, language/dsl/src/types.ts
Added WithApplicability, WithPlayerTypes, and ObjectWithIndexTracking as part of https://github.com/player-ui/player/pull/367
=> Added additional DSL types and component

.circleci/config.yml
Use JS only docker image for build
=> Use Slim Bazel Image

devtools/plugins/desktop/basic/src/content/views/FlowView.tsx, package.json, pnpm-lock.yaml
Updated @devtools-ui/plugin to version `0.3.0`, in order to show an object prop path filter in the Devtools plugin browser Flow panel.
=> [Devtools]FlowPanel/ObjectInspector/PathFilter

devtools/plugins/desktop/template/BUILD.hbs, devtools/plugins/desktop/template/README.md.hbs, devtools/plugins/desktop/template/_generated/index.json, devtools/plugins/desktop/template/package.json.hbs, devtools/plugins/desktop/template/src/WrapperComponent.tsx.hbs, devtools/plugins/desktop/template/src/constants/index.ts.hbs, devtools/plugins/desktop/template/src/content/common/Screen.tsx.hbs, devtools/plugins/desktop/template/src/content/common/index.ts.hbs, devtools/plugins/desktop/template/src/content/index.ts.hbs, devtools/plugins/desktop/template/src/content/navigation/index.ts.hbs, devtools/plugins/desktop/template/src/content/schema/index.ts.hbs, devtools/plugins/desktop/template/src/content/views/View1.tsx.hbs, devtools/plugins/desktop/template/src/content/views/View2.tsx.hbs, devtools/plugins/desktop/template/src/content/views/index.ts.hbs, devtools/plugins/desktop/template/src/helpers/__tests__/genDataChangeTransaction.test.ts.hbs, devtools/plugins/desktop/template/src/helpers/genDataChangeTransaction.ts.hbs, devtools/plugins/desktop/template/src/helpers/index.ts.hbs, devtools/plugins/desktop/template/src/index.tsx.hbs, devtools/plugins/desktop/template/tsconfig.json.hbs, devtools/plugins/desktop/test-env/package.json, package.json, plopfile.mjs, pnpm-lock.yaml, scripts/plopfile.mjs
Adds a generator to facilitate adding new dev tools web plugins:
```bash
pnpm gen:dev-tools-web-plugin
```
https://github.com/player-ui/tools/assets/26394217/a18fc484-2021-488f-90db-bb561e98888f
Adds a generator to facilitate adding new dev tools web plugins:
```bash
pnpm gen:dev-tools-web-plugin
```
=> #132 - Adds a dev tools web plugin generator

.github/workflows/canary.yml
the `context` is populated by the webhooks contents for what triggers it, which in this case is a comment, so theres no real info on the PR. swap the check down to pull the owner details from the head PR info
=> Fix Canary workflow for forks

.github/workflows/canary.yml
I read the [CircleCI API Docs](https://circleci.com/docs/api/v2/index.html#operation/triggerPipeline) this time
=> trigger forked PR canary in correct format for CircleCI

language/json-language-service/src/xlr/__tests__/__snapshots__/transform.test.ts.snap, language/json-language-service/src/xlr/transforms.ts
Closes #182 
Validation - Run `applyValueRefs` for Views and Transform `type` Properties
=> Run `applyValueRefs` for Views and Transform `type` Properties

.bazelignore, language/dsl-lite/BUILD, language/dsl-lite/README.md, language/dsl-lite/package.json, language/dsl-lite/src/__tests__/intrinsic-tags.test.tsx, language/dsl-lite/src/__tests__/nodes.test.ts, language/dsl-lite/src/__tests__/render.test.tsx, language/dsl-lite/src/__tests__/tagged-templates.test.ts, language/dsl-lite/src/index.ts, language/dsl-lite/src/jsx-runtime.ts, language/dsl-lite/src/jsx-types.d.ts, language/dsl-lite/src/nodes.ts, language/dsl-lite/src/render.ts, language/dsl-lite/src/tagged-templates.ts, language/dsl-lite/src/types.ts, language/dsl-lite/tsconfig.json, language/dsl-lite/tsup.config.ts, pnpm-lock.yaml, pnpm-workspace.yaml
fix #197
fix #198 
Creates a new package in the [player-ui/tools/language](https://github.com/player-ui/tools/tree/main/language) directory called dsl-lite that will serve as our lightweight JSX compiler for Player-UI content. This package will provide a performant alternative to the current React-based DSL compilation approach ([RFC](https://github.com/orgs/player-ui/discussions/617)).
Check the language/dsl-lite/README.md for more information.
=> DSL-Lite basic implementation

xlr/utils/package.json
Fix `@player-tools/xlr-utils` dependency on non-published package `@player-tools/test-utils` which is only needed as part of tests
=> Fix deps for utils on non-published package

scripts/release-info.js
Using auto's `getPrNumberFromEnv` to verify that the release-version-info script will only run in PR contexts.
=> Fixing release errors

.github/CODEOWNERS, language/dsl/src/index.ts
Fix export of `testExpression` function from `@player-tools/dsl` package
=> Fix Export of `testExpression` Function
