language/service/src/xlr/__tests__/__snapshots__/transform.test.ts.snap, language/service/src/xlr/__tests__/transform.test.ts, language/service/src/xlr/transforms.ts, xlr/converters/src/__tests__/__snapshots__/player.test.ts.snap, xlr/converters/src/ts-to-xlr.ts, xlr/sdk/src/index.ts, xlr/sdk/src/utils.ts, xlr/sdk/src/validator.ts, xlr/types/src/core.ts, xlr/types/src/utility.ts
Adds a basic walker function to walk an XLR tree, looking for a specific node type, and run a function to transform that node. This should make basic TransfromFunctions much easier to write as now all the traversal logic is abstracted away.  #3 
Adds a helper function to make writing recursive TransfromFunctions easier.
=> Recursive Transform Helper

xlr/converters/src/__tests__/__snapshots__/ts-to-common.test.ts.snap, xlr/converters/src/__tests__/ts-to-common.test.ts, xlr/converters/src/ts-to-xlr.ts
Fixes a bug where only one heritage class expression would be parsed out and merged into the object being converted. 
Fixed a bug with interfaces that extended more than one other interface.
=> Fix only one heritage class being parsed

cli/BUILD
Fixes errors in projects using typescript < 4.8
<details>
<summary>📦 Published PR as canary version: <code>0.2.2--canary.19.409</code></summary>
<br />
Try this version out locally by upgrading relevant packages to 0.2.2--canary.19.409
</details>
=> Pin typescript version in cli now that we're using new features.

.circleci/config.yml, webpack.config.js, xlr/converters/src/__tests__/__snapshots__/ts-to-common.test.ts.snap, xlr/converters/src/__tests__/ts-to-common.test.ts, xlr/converters/src/ts-to-xlr.ts
while trying to understand things for  #21 
i found that top level exported arrow functions with parameters crashed in a test, params in the synthetic `ts.TypeNode` have `-1` position information, and pretty much every other property is `undefined` including `text`, so `param.name.getText()` was crashing
i copied params onto the synthetic node from the original node
=> forward parameters to synthetic node for arrow functions with parameters

xlr/converters/src/__tests__/__snapshots__/ts-to-common.test.ts.snap, xlr/converters/src/__tests__/ts-to-common.test.ts, xlr/converters/src/ts-to-xlr.ts
checks the effective type of the initializer statement to see if its a function, rather than a concrete type
if it is a function, we update the name to be the name of the exporting variable, not the name of the identifier it is aliasing
resolves #21
=> fix function aliasing exporting wrong name

cli/src/commands/xlr/compile.ts, cli/src/utils/xlr/consts.ts, cli/src/utils/xlr/visitors/file.ts, cli/src/utils/xlr/visitors/index.ts, cli/src/utils/xlr/visitors/plugin.ts, cli/src/utils/xlr/visitors/types.ts, xlr/converters/src/ts-to-xlr.ts
Fixes #22. Might not be the cleanest way but since the post XLR compile transforms are very specific, we can make certain assumptions and play a bit loose with some of the types. 
Player CLI - Fixes some Expressions that don't export with variable names.
=> Reorg xlr compile target, support player specific post processing

drag-and-drop/app/pages/index.tsx, drag-and-drop/library/src/__tests__/controller.test.tsx, drag-and-drop/library/src/controller.tsx, drag-and-drop/library/src/utils/helpers.ts, drag-and-drop/library/src/utils/runtime-flow-state.ts
pass a callback to handle Drag and Drop state changes
=> pass a callback to handle Drag and Drop state changes

drag-and-drop/app/pages/index.tsx, drag-and-drop/library/src/__tests__/controller.test.tsx, drag-and-drop/library/src/controller.tsx, drag-and-drop/library/src/types.ts
Currently any player plugin added needs a manifest as well.  This should only be for assets that need to be dragged and dropped.
- updated the config that is passed into the DragAndDropController so the manifest is passed in separately.
- verified tests are still green.
=> feat: added ability to add player plugins that don't have a manifest in dnd library

cli/src/utils/babel-register.ts
Add missing `require.resolve` on resolution of `@babel/plugin-transform-react-jsx-source` in cli causing issues when compiling content
=> add missing resolve in cli

cli/src/commands/json/validate.ts, cli/src/plugins/LSPAssetsPlugin.ts, language/json-language-service/src/plugins/__tests__/nav-state-plugin.test.ts, language/json-language-service/src/plugins/xlr-plugin.ts, xlr/converters/src/__tests__/__snapshots__/ts-to-common.test.ts.snap, xlr/converters/src/__tests__/ts-to-common.test.ts, xlr/converters/src/ts-to-xlr.ts, xlr/sdk/src/sdk.ts, xlr/sdk/src/validator.ts, xlr/utils/src/__tests__/__snapshots__/validation-helpers.test.ts.snap, xlr/utils/src/__tests__/validation-helpers.test.ts, xlr/utils/src/ts-helpers.ts, xlr/utils/src/validation-helpers.ts
Misc improvements found when benchmarking XLR validations
Currently, types that use the `Excludes` keywords results in a mapped type getting produced that may or may not resolve well at runtime. Since this is a keyword that we can parse at compile time like `Omit` or `Pick` we should be handling this directly. 
When we access a type from the SDK, we do some computations to figure out what the effective object is once `extends` and generics are filled in. We don't need to do that work every time if the types in the SDK have not changed so we can cache those results and return them instead. 
Previously, an LSP was instantiated per file being validated, this lead to a lot of overhead when validating multiple files and, given the amount of XLR data being loaded, proved to be a bottleneck. …
=> Validation Improvements

cli/package.json
Fix cli package.json main/typings entrypoints
=> Fix cli package.json

xlr/asset-docgen-webpack-plugin/src/index.ts
FIx XLR Webpack plugin loading XLRs from `node_modules`
=> Fix loading XLRs from node_modules in webpack plugin

MODULE.bazel, cli/BUILD, cli/package.json
Fix custom entry points being overridden in CLI package
=> Use New Rules to Skip Custom Entrypoint Insertion for CLI

xlr/asset-docgen-webpack-plugin/src/index.ts
Storybook Plugin - Fix linting issues, doc export collision if two XLRs are exported from the same package, and not having player xlr types loaded when parsing types
=> Fix issues with storybook plugin and storybook 6.5.x

.circleci/config.yml
Maintenance updates to the circle config to 
- Skip redundant test/coverage steps which should cut ~3m from the build
=> Update Circle Configs

MODULE.bazel, cli/BUILD, cli/package.json
The conflg and dependency for the `@oclif/plugins-plugin` was misapplied so plugins were not able to be registered to the oclif plugin. 
- Fix Oclif plugins not registering
- Use shared Oclif macro for CLI build
<details>
<summary>📦 Published PR as canary version: <code>0.5.2--canary.94.2360</code></summary>
<br />
Try this version out locally by upgrading relevant packages to 0.5.2--canary.94.2360
</details>
=> Fix Oclif CLI Plugins not Registering

pnpm-lock.yaml
Updates the `MODULE.bazel.lock` and `pnpm-lock.yaml`.
<details>
<summary>📦 Published PR as canary version: <code>0.5.3--canary.100.2570</code></summary>
<br />
Try this version out locally by upgrading relevant packages to 0.5.3--canary.100.2570
</details>
=> chore: update locks

language/dsl/src/__tests__/edge-cases.test.tsx, language/dsl/src/utils.tsx
Currently, if you try and use an intermediate part of the schema in content, it may or may not serialize correctly. For example the binding `some` from the schema 
```typescript 
const schema = {
some: [
{
value: {...},
value2: {...}
}
]
}
```
was used, an error would be thrown [here](https://github.com/player-ui/tools/blob/845938fa01eceef2aedb1748a8810814815dca16/language/dsl/src/utils.tsx#L21) as `makeBindingsForObject` would proxy that element into an _array-like_ object that would be caught by that check but wouldn't actually be serializable. With this change, we move the check for if the value being processed is a `TemplateStringType` that we should handle directly before processing it as a regular piece of content.  
While technically loading complex data structures from the data …
=> Handle Template Strings Earlier in DSL Compilation

xlr/utils/src/__tests__/validation-helpers.test.ts, xlr/utils/src/validation-helpers.ts
Fixes a regression when validating an object where one key is escaped. As XLR will output escaped properties with a single quote, if the mapped properties set has the escaped key in double quotes it will not find the property and thus may lead to an error. This bug was most likely introduced when we changed the prettier config to prefer double quotes over single quotes. The conversion must not have ignored quotes in string templates. 
XLR - Fixes validation of objects where a property is escaped using single/double quotes and the property is required or the object doesn't allow additional properties. 
<details>
<summary>📦 Published PR as canary version: <code>0.6.1--canary.110.2690</code></summary>
<br />
Try this version out locally by …
=> Fix Regression on Validation of Keys with Escaped Characters

xlr/converters/src/__tests__/__snapshots__/ts-to-common.test.ts.snap, xlr/converters/src/__tests__/ts-to-common.test.ts, xlr/converters/src/ts-to-xlr.ts
When parsing `IndexedAccessType` nodes, the current check of the `objectType` property  being  a `TypeQuery` node doesn't handle the cases where it may be wrapped in a `ParenthesizedTypeNode`. While functionally the same, the check doesn't account for it and causes an error to be thrown. This adds a simple check for that type of node and will use its child if present. 
XLR - Fixed compilation of `IndexedAccesNodes `that use parentheses around the first element.
=> Fix Parsing Indexed Access Types with Parentheses 

devtools/client/src/panel/index.tsx, devtools/plugins/desktop/test-env/setup.sh, package.json
This bumps the version of devtools and fixes the panel width. 
Switched from stack to Flex ->
"The Stack component and the Flex component have their children spaced out evenly but the key difference is that the Stack won't span the entire width of the container whereas the Flex will."
=> Devtools- panel layout fix and version upgrade

xlr/sdk/src/validator.ts
Check against `null` instead of `"null"` when validating a `NullType`
Validator - Properly validate `NullType` nodes against `null` literals
=> Fix Bug when Validating `null` literals

language/json-language-service/src/__tests__/__snapshots__/service.test.ts.snap, language/json-language-service/src/plugins/asset-wrapper-array-plugin.ts, language/json-language-service/src/xlr/__tests__/__snapshots__/transform.test.ts.snap, language/json-language-service/src/xlr/transforms.ts, xlr/converters/src/__tests__/__snapshots__/player.test.ts.snap, xlr/converters/src/ts-to-xlr.ts, xlr/sdk/src/__tests__/__snapshots__/sdk.test.ts.snap, xlr/sdk/src/__tests__/sdk.test.ts, xlr/sdk/src/sdk.ts, xlr/sdk/src/utils.ts, xlr/sdk/src/validator.ts, xlr/utils/src/ts-helpers.ts, xlr/utils/src/validation-helpers.ts
Currently there is an issue if when the generated `template` properties are validated where because the XLR node isn't fully resolved when retrieved from the SDK by the language service, it can't be fully walked to determine what acutually should be there. This PR now makes it so, by default unless disabled, returned a fully resolved XLR from the SDK. This entails resolving:
- `AndTypeNode` which represent type intersections
- `ConditionalTypeNode` which represent dynamic conditional types
- `RefTypeNode` which represent references to other named types
Doing this allows the XLR returned by the SDK to be parsed easier as it is a more complete look at the actual underlying type. As a result of this, validation gets much faster as nodes are now fully resolved once then cached which means …
=> Fix Issue Validating Templates

devtools/plugins/mobile/flipper-desktop-client/BUILD, devtools/plugins/mobile/flipper-desktop-client/package.json
Bazel build file updates on the `flipper-plugin-player-ui-devtools ` package to get to publish to npm registry again.
<details>
<summary>📦 Published PR as canary version: <code>0.6.1--canary.138.3286</code></summary>
<br />
Try this version out locally by upgrading relevant packages to 0.6.1--canary.138.3286
</details>
=> [bazel - npm registry] flipper-plugin-player-ui-devtools

.circleci/config.yml, .github/workflows/canary.yml
Whenever we branched the tools repo; the build_and_test_pr would fail. This should allow us to build from forks
=> [circleCI] allows us to build from forks

.github/workflows/canary.yml
Removed the check to make a canary on forks. This check was potentially causing the canary not to release when branches were not from a fork.
=> revert canary on forks

cli/src/commands/dsl/compile.ts, cli/src/utils/compilation-context.ts
Currently, the CLI assumes that any result from the compilation hook is an object that can be serialized to JSON and should be written to a file that ends in `.js`. There are potentially other usecases for compiling Player related content that may not result in a JSON serializable result. This PR expands the results to generalize what the compilation is to be some string that should be written as the output file, and an optional second string that should be written as the source map. 
Allow DSL compilation phase to compile to non `.json` targets
<details>
<summary>📦 Published PR as canary version: <code>0.7.0--canary.146.3413</code></summary>
<br />
Try this version out locally by upgrading relevant packages to 0.7.0--canary.146.3413 …
=> Update CLI to Allow Compilation to any File Type

cli/src/utils/compilation-context.ts
#146 had a side-effect of removing white space formatting from compiled content. This inadvertently breaks downstream tooling relying on multi-line formatted content. We'll need to re-evaluate the strategy, but this change unblocks upgrades until that is done.
The miss:
https://github.com/player-ui/tools/pull/146/files#diff-1c41b0a3b4f66722dbb6de6aa0db4a7217ddfcbe227ad77e1fc2d8465df2764bL144
https://github.com/player-ui/tools/pull/146/files#diff-8c9606b0dba073f9d586e0e29ded3b630c37916c172f55eb7e6e12d288a2d9b7R70
<details>
<summary>📦 Published PR as canary version: <code>0.7.1--canary.153.3460</code></summary>
<br />
Try this version out locally by upgrading relevant packages to 0.7.1--canary.153.3460
</details>
=> Re-add compiler formatting to dsl output

cli/bin/dev, cli/bin/run
Setting the node env to `production` prevents source maps from being generated by the [react-json-reconciler](https://github.com/intuit/react-json-reconciler)
<!--
To include release notes in the automatic changelong, just add a level 1 markdown header below
and include any markdown notes to go into the changelog: https://intuit.github.io/auto/docs/generated/changelog#additional-release-notes
Fix source maps not being generated for DSL content when compiled by the cli
=> Fix Source Maps not Being Generated for DSL Content

cli/src/commands/dsl/compile.ts, cli/src/commands/dsl/validate.ts
Adds an option to avoid exiting with code 1 if there's a validation error, but the severity of the DSL validation is set to `warn`.
=> feat: doesn't exit with error if warn-only on dsl validation

.circleci/config.yml
Use bazelrc to include CI bazel configuration for builds off of main 
=> Use bazelrc for Main Builds

cli/BUILD, cli/package.json
Closes #167. A manifest is not technically required so instead of figuring out how to stamp it correctly we can just remove it from the generation pipeline. 
Fixes issue with oclif manifest not being stamped with the right version leading to console errors
=> Don't create oclif manifest

cli/src/plugins/LSPAssetsPlugin.ts, cli/src/plugins/__tests__/LSPAssetsPlugin.test.ts
Closes #98 
Allow for loading XLRs to LSP via module imports. Add explicit (optional for now) toggle for distinguishing between module and manifest loading.
=> Add options to LSPAssetsPlugin to load from TSManifest via module import

cli/BUILD, cli/src/commands/dsl/compile.ts, package.json, pnpm-lock.yaml
- Remove unneeded dependency `@oclif/plugin-legacy`
- Fix issue with how the DSL compilation command passed arguments to the JSON validation plugin
<details>
<summary>📦 Published PR as canary version: <code>0.8.2--canary.178.3944</code></summary>
<br />
Try this version out locally by upgrading relevant packages to 0.8.2--canary.178.3944
</details>
=> Remove Unneeded Dependency

language/dsl/src/__tests__/template.test.tsx, language/dsl/src/template.tsx
Fix an issue where Template components in slots that contained a static element wouldn't be serialized to JSON in the same order they were authored in.
=> Preserve Order of Templates in Slots

.autorc, scripts/next-changelogs.js
Keep information about `next` release in changelog
=> Add Support for Retaining `next` Release Information in Changelogs

.circleci/config.yml
Fixing an issue where the CI was erroring out when there was no PR (when a PR is going into main, etc).
Caused by https://github.com/player-ui/tools/pull/203
<details>
<summary>📦 Published PR as canary version: <code>0.9.1--canary.205.4524</code></summary>
<br />
Try this version out locally by upgrading relevant packages to 0.9.1--canary.205.4524
</details>
=> PR Comment Version Fix

language/dsl-lite/src/__tests__/useRef.test.tsx, language/dsl-lite/src/hooks.ts, language/dsl-lite/src/types.ts
fix #200 
Implement a `useRef` hook that allows content authors to access AST nodes directly. This will provide a way for authors to get references to AST nodes for advanced use cases.
=> feat: add useRef to the dsl-lite

pnpm-lock.yaml, xlr/converters/package.json
Fix `@player-tools/xlr-converters` dependency on non-published package `@player-tools/test-utils` which is only needed as part of tests.
Related to https://github.com/player-ui/tools/pull/211
<details>
<summary>📦 Published PR as canary version: <code>0.10.2--canary.215.4733</code></summary>
<br />
Try this version out locally by upgrading relevant packages to 0.10.2--canary.215.4733
</details>
=> Fix deps for utils for xlr converters package

language/metrics-output-plugin/BUILD, language/metrics-output-plugin/package.json, language/metrics-output-plugin/src/__tests__/metrics-output-plugin.test.ts, language/metrics-output-plugin/src/metrics-output.ts, language/metrics-output-plugin/src/types.ts, package.json, pnpm-lock.yaml
Updating metrics output plugin so that the output file correctly updates and aggregates data if there are multiple times that validation occurs. This uses ts-deepmerge to ensure nested objects are merged correctly, and also groups all rootProperties before content.
<details>
<summary>📦 Published PR as canary version: <code>0.12.1--canary.222.5311</code></summary>
<br />
Try this version out locally by upgrading relevant packages to 0.12.1--canary.222.5311
</details>
=> feat: Metrics Output Plugin should aggregate data

cli/src/commands/dsl/compile.ts, cli/src/config.ts, cli/src/utils/compilation-context.ts
- Adds a new hook to `CompilationContext` to allow plugins to indicate files that should skip the dsl compilation step
- Added `skipCompilation` hook to `CompilationContext` to determine if a file should be skipped during compilation
- Added a check in `compileFile` to skip compilation if hook returns true
- Add a new hook `skipCompilation` for `player dsl compile`, allowing plugins to indicate files to skip dsl compilation step
=> feat: add hook to support skipCompilation for dsl compilation
